-- Seed data for CareerBridge application
-- This file contains sample data for testing and development

-- Insert sample jobs
INSERT INTO jobs (job_title, company, location, job_description, required_skills, experience_level, job_type, salary_min, salary_max, responsibilities, requirements, benefits) VALUES
('Frontend Developer', 'Tech Solutions Inc', 'Remote', 'We are seeking a talented Frontend Developer to join our dynamic team. You will be responsible for building responsive and user-friendly web applications using modern JavaScript frameworks. Collaborate with designers and backend developers to create seamless user experiences.', ARRAY['JavaScript', 'React', 'CSS', 'HTML'], 'junior', 'full_time', 60000, 80000, ARRAY['Develop and maintain responsive web applications using React', 'Collaborate with UX/UI designers to implement pixel-perfect designs', 'Write clean, maintainable, and well-documented code', 'Participate in code reviews and contribute to team knowledge sharing', 'Optimize application performance and ensure cross-browser compatibility'], ARRAY['1-2 years of experience with JavaScript and React', 'Strong understanding of HTML5, CSS3, and responsive design principles', 'Experience with version control systems (Git)', 'Good problem-solving skills and attention to detail', 'Bachelor''s degree in Computer Science or related field (or equivalent experience)'], ARRAY['Flexible remote work arrangement', 'Health, dental, and vision insurance', 'Professional development budget', '401(k) with company match', 'Generous PTO policy']),
('Full Stack Developer', 'Innovation Labs', 'New York, NY', 'Join our innovative team as a Full Stack Developer! You will work on cutting-edge projects, developing both frontend and backend solutions. Experience with modern web technologies and cloud platforms is essential. Great opportunity for growth and learning.', ARRAY['JavaScript', 'Node.js', 'React', 'PostgreSQL', 'Docker'], 'mid', 'full_time', 90000, 120000, ARRAY['Design and develop full-stack web applications', 'Build and maintain RESTful APIs', 'Implement database schemas and optimize queries', 'Deploy and manage containerized applications', 'Mentor junior developers and conduct code reviews'], ARRAY['3-5 years of full-stack development experience', 'Proficiency in JavaScript, Node.js, and React', 'Strong experience with SQL databases (PostgreSQL preferred)', 'Familiarity with Docker and containerization', 'Experience with cloud platforms (AWS, Azure, or GCP)', 'Excellent communication and teamwork skills'], ARRAY['Competitive salary with annual bonuses', 'Comprehensive health benefits', 'Stock options', 'Hybrid work model', 'Learning and development stipend', 'Team building events and company outings']),
('Junior Web Developer', 'Startup Hub', 'San Francisco, CA', 'Start your career with us! This internship offers hands-on experience building real web applications. Learn from experienced developers while working on exciting startup projects. Perfect for recent graduates or career changers.', ARRAY['HTML', 'CSS', 'JavaScript'], 'fresher', 'internship', 20000, 30000, ARRAY['Assist in developing web pages and user interfaces', 'Write clean HTML, CSS, and JavaScript code', 'Test websites across different browsers and devices', 'Debug and fix frontend issues', 'Participate in team meetings and learning sessions'], ARRAY['Basic knowledge of HTML, CSS, and JavaScript', 'Passion for web development and willingness to learn', 'Strong attention to detail', 'Good communication skills', 'Currently pursuing or recently completed degree in related field'], ARRAY['Mentorship from senior developers', 'Hands-on experience with real projects', 'Flexible internship hours', 'Potential for full-time employment', 'Free snacks and beverages']),
('React Developer', 'Digital Agency', 'Austin, TX', 'We need a React specialist to build modern, performant web applications for our diverse client base. You will work with the latest React ecosystem tools and best practices. Strong communication skills and attention to detail required.', ARRAY['React', 'JavaScript', 'TypeScript', 'Redux'], 'junior', 'full_time', 65000, 85000, ARRAY['Build reusable React components and front-end libraries', 'Implement state management using Redux or Context API', 'Optimize components for maximum performance', 'Collaborate with clients to understand requirements', 'Write unit and integration tests'], ARRAY['2+ years of experience with React and JavaScript', 'Proficiency in TypeScript', 'Experience with Redux or other state management libraries', 'Understanding of modern JavaScript (ES6+)', 'Familiarity with testing frameworks like Jest or React Testing Library'], ARRAY['Health and wellness benefits', 'Work from home Fridays', 'Professional development opportunities', 'Annual performance bonuses', 'Collaborative team environment']),
('Backend Developer', 'Cloud Systems', 'Seattle, WA', 'Looking for an experienced Backend Developer to architect and implement scalable server-side solutions. Work with microservices, databases, and cloud infrastructure. Join a team that values code quality and continuous improvement.', ARRAY['Node.js', 'Python', 'PostgreSQL', 'AWS'], 'mid', 'full_time', 95000, 130000, ARRAY['Design and implement scalable backend services', 'Build RESTful APIs and microservices architecture', 'Optimize database performance and write complex queries', 'Deploy and manage services on AWS infrastructure', 'Implement security best practices and authentication systems'], ARRAY['4+ years of backend development experience', 'Strong proficiency in Node.js and Python', 'Deep understanding of SQL and database design', 'Experience with AWS services (EC2, S3, Lambda, RDS)', 'Knowledge of API design and microservices patterns', 'Experience with CI/CD pipelines'], ARRAY['Competitive compensation package', 'Comprehensive health coverage', 'Stock options', 'Remote work flexibility', 'Unlimited PTO', 'Conference and training budget']),
('Data Analyst', 'Analytics Corp', 'Boston, MA', 'Analyze complex datasets to drive business decisions. Create insightful reports and dashboards using Python and visualization tools. Work closely with stakeholders to understand their data needs and deliver actionable insights.', ARRAY['Python', 'SQL', 'Pandas', 'Excel', 'Tableau'], 'junior', 'full_time', 55000, 75000, ARRAY['Collect, clean, and analyze large datasets', 'Create interactive dashboards and visualizations in Tableau', 'Write SQL queries to extract and manipulate data', 'Generate reports and present findings to stakeholders', 'Identify trends and patterns to support business decisions'], ARRAY['1-3 years of experience in data analysis', 'Proficiency in SQL and Python', 'Experience with Pandas and data manipulation', 'Strong skills in Excel (pivot tables, formulas, charts)', 'Familiarity with Tableau or similar BI tools', 'Bachelor''s degree in a quantitative field'], ARRAY['Health and dental insurance', 'Flexible work hours', '401(k) plan', 'Professional development courses', 'Casual work environment']),
('Junior Data Scientist', 'AI Innovations', 'Remote', 'Exciting opportunity to start your data science career! Work on machine learning projects, conduct statistical analysis, and help build predictive models. Mentorship provided by senior data scientists. Perfect for those passionate about AI and data.', ARRAY['Python', 'Machine Learning', 'Statistics', 'SQL'], 'fresher', 'internship', 25000, 35000, ARRAY['Assist in developing machine learning models', 'Perform exploratory data analysis', 'Clean and preprocess datasets', 'Contribute to model evaluation and improvement', 'Document processes and findings'], ARRAY['Strong foundation in statistics and mathematics', 'Knowledge of Python and machine learning libraries (scikit-learn, pandas)', 'Basic SQL skills', 'Familiarity with Jupyter notebooks', 'Pursuing or recently completed degree in Data Science, Statistics, or related field'], ARRAY['Remote work flexibility', 'Mentorship program with senior data scientists', 'Access to cutting-edge AI tools and platforms', 'Opportunity for full-time conversion', 'Learning resources and courses']),
('Data Engineer', 'BigData Solutions', 'Chicago, IL', 'Build and maintain robust data pipelines and ETL processes. Work with big data technologies to process and transform large-scale datasets. Ensure data quality and optimize performance for analytics workloads.', ARRAY['Python', 'SQL', 'Apache Spark', 'AWS', 'ETL'], 'mid', 'full_time', 100000, 135000, ARRAY['Design and implement scalable data pipelines', 'Develop ETL processes to integrate data from multiple sources', 'Work with Apache Spark for big data processing', 'Optimize data warehouse performance', 'Collaborate with data scientists and analysts to meet data requirements', 'Monitor and troubleshoot data pipeline issues'], ARRAY['3-5 years of experience in data engineering', 'Strong proficiency in Python and SQL', 'Experience with Apache Spark or similar big data frameworks', 'Knowledge of AWS data services (Redshift, Glue, EMR)', 'Understanding of data warehousing concepts', 'Experience with ETL tools and processes'], ARRAY['Competitive salary and bonuses', 'Comprehensive health benefits', 'Remote work options', 'Stock options', 'Learning and certification reimbursement', 'Gym membership']),
('UI/UX Designer', 'Creative Studio', 'Los Angeles, CA', 'Design beautiful and intuitive user interfaces for web and mobile applications. Conduct user research, create wireframes and prototypes, and work closely with developers to bring designs to life. Portfolio required.', ARRAY['Figma', 'Adobe XD', 'Sketch', 'User Research'], 'junior', 'full_time', 60000, 80000, ARRAY['Create user-centered designs for web and mobile applications', 'Conduct user research and usability testing', 'Develop wireframes, prototypes, and high-fidelity mockups', 'Collaborate with developers to ensure design implementation', 'Maintain and evolve design systems'], ARRAY['2+ years of UI/UX design experience', 'Proficiency in Figma, Adobe XD, or Sketch', 'Strong portfolio demonstrating design process and outcomes', 'Understanding of user research methodologies', 'Knowledge of responsive design principles', 'Excellent communication and collaboration skills'], ARRAY['Creative and collaborative work environment', 'Health and wellness benefits', 'Flexible hours', 'Professional development budget', 'Modern design tools and equipment']),
('Graphic Designer', 'Marketing Agency', 'Miami, FL', 'Create stunning visual content for various marketing campaigns. Design logos, social media graphics, and promotional materials. Collaborate with the marketing team to deliver creative solutions that meet client objectives.', ARRAY['Adobe Photoshop', 'Illustrator', 'InDesign', 'Branding'], 'fresher', 'part_time', 30000, 40000, ARRAY['Design graphics for social media, print, and digital campaigns', 'Create brand identities including logos and style guides', 'Produce marketing materials such as brochures and flyers', 'Collaborate with marketing team on creative concepts', 'Edit and retouch images for various purposes'], ARRAY['Portfolio showcasing graphic design work', 'Proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign)', 'Understanding of branding and visual identity', 'Creativity and attention to detail', 'Ability to work on multiple projects simultaneously'], ARRAY['Flexible part-time schedule', 'Opportunity to work on diverse projects', 'Access to Adobe Creative Cloud', 'Portfolio-building opportunities', 'Potential for full-time position']),
('Product Designer', 'Tech Products Co', 'San Diego, CA', 'Lead the design of innovative product features from concept to launch. Create and maintain design systems, conduct user testing, and iterate based on feedback. Work in a collaborative environment with product managers and engineers.', ARRAY['Figma', 'Prototyping', 'User Testing', 'Design Systems'], 'mid', 'full_time', 85000, 110000, ARRAY['Lead end-to-end product design from concept to launch', 'Create and maintain comprehensive design systems', 'Conduct user interviews and usability testing', 'Design interactive prototypes for user testing', 'Collaborate with product and engineering teams', 'Present design rationale and gather feedback from stakeholders'], ARRAY['4+ years of product design experience', 'Expert proficiency in Figma', 'Strong experience with design systems', 'Proven track record of shipping successful products', 'Excellent prototyping and user testing skills', 'Strong communication and presentation abilities'], ARRAY['Competitive salary with equity', 'Comprehensive health coverage', 'Flexible hybrid work model', 'Latest design tools and equipment', 'Conference attendance support', 'Generous vacation policy']),
('Digital Marketing Specialist', 'Growth Marketing', 'Denver, CO', 'Drive online growth through comprehensive digital marketing strategies. Manage SEO campaigns, analyze web traffic, and create engaging content. Help businesses reach their target audience and achieve their marketing goals.', ARRAY['SEO', 'Google Analytics', 'Content Marketing', 'Social Media'], 'junior', 'full_time', 50000, 70000, ARRAY['Develop and execute SEO strategies to improve organic rankings', 'Manage and optimize Google Ads and social media campaigns', 'Create engaging content for blogs and social media', 'Analyze website traffic and campaign performance using Google Analytics', 'Generate monthly reports on marketing metrics'], ARRAY['1-3 years of digital marketing experience', 'Strong understanding of SEO best practices', 'Proficiency with Google Analytics and Google Ads', 'Experience with content creation and copywriting', 'Knowledge of social media platforms and marketing strategies', 'Analytical mindset with attention to detail'], ARRAY['Health and dental insurance', 'Professional development opportunities', 'Flexible work schedule', 'Performance bonuses', 'Collaborative team culture']),
('Social Media Manager', 'Brand Agency', 'Portland, OR', 'Build and engage online communities for exciting brands. Create compelling social media content, monitor trends, and analyze performance metrics. Great opportunity for creative storytellers passionate about social media.', ARRAY['Social Media Strategy', 'Content Creation', 'Analytics', 'Copywriting'], 'fresher', 'part_time', 25000, 35000, ARRAY['Create and schedule engaging social media content', 'Monitor social media channels and respond to comments', 'Track social media metrics and prepare performance reports', 'Stay current with social media trends and platform updates', 'Collaborate with design team on visual content'], ARRAY['Strong understanding of major social media platforms', 'Excellent writing and communication skills', 'Creative mindset and storytelling ability', 'Basic knowledge of social media analytics', 'Experience with social media management tools (Buffer, Hootsuite)', 'Portfolio of social media content or campaigns'], ARRAY['Flexible part-time hours', 'Remote work option', 'Creative freedom', 'Networking opportunities', 'Potential for growth into full-time role']),
('Marketing Analyst', 'E-commerce Giant', 'Remote', 'Leverage data to optimize marketing campaigns and improve ROI. Conduct A/B tests, create dashboards, and provide actionable recommendations. Work with cross-functional teams in a fast-paced e-commerce environment.', ARRAY['Google Analytics', 'Excel', 'SQL', 'A/B Testing', 'Data Visualization'], 'junior', 'full_time', 55000, 75000, ARRAY['Analyze marketing campaign performance across channels', 'Design and execute A/B tests to optimize conversion rates', 'Build dashboards to track key marketing metrics', 'Provide data-driven recommendations to marketing team', 'Create reports on customer behavior and trends'], ARRAY['2+ years of experience in marketing analytics', 'Proficiency in Google Analytics and Excel', 'SQL skills for data extraction and analysis', 'Experience with A/B testing methodologies', 'Familiarity with data visualization tools (Tableau, Power BI)', 'Strong analytical and problem-solving skills'], ARRAY['Fully remote position', 'Competitive salary and bonuses', 'Health benefits', 'Employee discounts', 'Career growth opportunities', 'Work-life balance']),
('Content Marketing Manager', 'SaaS Company', 'Nashville, TN', 'Develop and execute content strategies that drive customer acquisition and engagement. Create blog posts, whitepapers, and email campaigns. Manage content calendar and measure content performance. SEO expertise essential.', ARRAY['Content Strategy', 'SEO', 'Copywriting', 'Email Marketing'], 'mid', 'full_time', 75000, 95000, ARRAY['Develop comprehensive content marketing strategies', 'Create high-quality blog posts, whitepapers, and case studies', 'Manage editorial calendar and content production workflow', 'Optimize content for SEO and search visibility', 'Design and execute email marketing campaigns', 'Measure content performance and ROI'], ARRAY['4+ years of content marketing experience', 'Proven track record of successful content campaigns', 'Excellent writing and editing skills', 'Strong SEO knowledge and experience', 'Experience with email marketing platforms', 'Ability to manage multiple projects and deadlines'], ARRAY['Competitive salary', 'Health and wellness benefits', 'Hybrid work model', 'Professional development budget', 'Stock options', 'Collaborative culture']),
('Web Designer', 'Design Collective', 'Philadelphia, PA', 'Design modern, responsive websites for diverse clients. Transform ideas into beautiful web experiences using the latest design tools and front-end technologies. Freelance role with flexible hours and competitive rates.', ARRAY['HTML', 'CSS', 'Figma', 'Responsive Design', 'WordPress'], 'junior', 'freelance', NULL, NULL, ARRAY['Design responsive websites for various clients', 'Create wireframes and mockups in Figma', 'Implement designs using HTML and CSS', 'Customize WordPress themes and plugins', 'Collaborate with clients to understand their needs'], ARRAY['2+ years of web design experience', 'Strong portfolio of website designs', 'Proficiency in HTML, CSS, and Figma', 'Experience with WordPress', 'Understanding of responsive design principles', 'Self-motivated and able to work independently'], ARRAY['Flexible freelance schedule', 'Work from anywhere', 'Competitive project-based compensation', 'Diverse portfolio of projects', 'Opportunity for ongoing client relationships']),
('Python Developer', 'FinTech Startup', 'Remote', 'Build secure and scalable financial applications using Python and Django. Work on RESTful APIs, integrate payment systems, and ensure code quality. Join a startup that is revolutionizing personal finance.', ARRAY['Python', 'Django', 'REST APIs', 'PostgreSQL'], 'junior', 'full_time', 70000, 90000, ARRAY['Develop backend services using Python and Django', 'Build and maintain RESTful APIs', 'Integrate third-party payment and financial APIs', 'Write unit tests and maintain code quality', 'Collaborate with frontend team on API contracts'], ARRAY['2+ years of Python development experience', 'Strong experience with Django framework', 'Knowledge of RESTful API design', 'Experience with PostgreSQL or similar databases', 'Understanding of financial systems is a plus', 'Familiarity with Git and agile development'], ARRAY['Fully remote work', 'Competitive salary with equity', 'Health insurance', 'Learning and development budget', 'Startup culture with rapid growth', 'Flexible working hours']),
('DevOps Engineer', 'Cloud Infrastructure', 'Dallas, TX', 'Automate infrastructure and streamline deployment processes. Manage containerized applications, implement CI/CD pipelines, and monitor system performance. Work with cutting-edge cloud technologies in a collaborative team.', ARRAY['Docker', 'Kubernetes', 'AWS', 'CI/CD', 'Linux'], 'mid', 'full_time', 95000, 125000, ARRAY['Design and maintain CI/CD pipelines', 'Manage Kubernetes clusters and containerized applications', 'Automate infrastructure provisioning using Infrastructure as Code', 'Monitor system performance and troubleshoot issues', 'Implement security best practices across infrastructure', 'Collaborate with development teams on deployment strategies'], ARRAY['3-5 years of DevOps or infrastructure experience', 'Strong experience with Docker and Kubernetes', 'Proficiency with AWS cloud services', 'Experience with CI/CD tools (Jenkins, GitLab CI, GitHub Actions)', 'Strong Linux administration skills', 'Knowledge of Infrastructure as Code (Terraform, CloudFormation)'], ARRAY['Competitive salary and bonuses', 'Health and wellness benefits', 'Hybrid work arrangement', 'Professional certifications support', 'Latest tech tools and equipment', 'Collaborative engineering culture']),
('QA Engineer', 'Software Testing Co', 'Atlanta, GA', 'Learn software testing from the ground up! Create test plans, execute manual and automated tests, and report bugs. Great internship for detail-oriented individuals looking to start a career in quality assurance.', ARRAY['Manual Testing', 'Selenium', 'JavaScript', 'Test Automation'], 'fresher', 'internship', 22000, 32000, ARRAY['Develop and execute test plans and test cases', 'Perform manual testing of web applications', 'Write automated tests using Selenium', 'Document and track bugs in issue tracking systems', 'Participate in agile ceremonies and sprint planning'], ARRAY['Basic understanding of software testing concepts', 'Familiarity with JavaScript', 'Knowledge of Selenium or willingness to learn', 'Strong attention to detail', 'Good communication skills', 'Pursuing or recently completed degree in Computer Science or related field'], ARRAY['Mentorship from experienced QA engineers', 'Hands-on experience with automation tools', 'Flexible internship schedule', 'Potential for full-time employment', 'Training on industry-standard tools']),
('Business Analyst', 'Consulting Firm', 'Washington DC', 'Bridge the gap between business needs and technical solutions. Gather requirements, create documentation, and work with development teams. Experience with Agile methodologies and strong analytical skills required.', ARRAY['Requirements Gathering', 'SQL', 'Excel', 'Agile', 'Documentation'], 'junior', 'full_time', 60000, 80000, ARRAY['Gather and document business requirements', 'Create user stories and acceptance criteria', 'Analyze business processes and identify improvement opportunities', 'Facilitate meetings between stakeholders and development teams', 'Create reports and dashboards using SQL and Excel'], ARRAY['2+ years of business analysis experience', 'Strong analytical and problem-solving skills', 'Proficiency in SQL for data analysis', 'Advanced Excel skills', 'Experience with Agile/Scrum methodologies', 'Excellent communication and documentation skills', 'Bachelor''s degree in Business, IT, or related field'], ARRAY['Health and dental insurance', 'Professional development opportunities', 'Hybrid work model', 'Performance bonuses', 'Retirement savings plan', 'Collaborative consulting environment']);

-- Insert sample learning resources
INSERT INTO learning_resources (title, platform, url, related_skills, cost) VALUES
-- Web Development
('Complete Web Development Bootcamp', 'Udemy', 'https://udemy.com/web-dev', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'], 'paid'),
('JavaScript - The Complete Guide', 'Udemy', 'https://udemy.com/javascript', ARRAY['JavaScript', 'ES6', 'DOM', 'Async'], 'paid'),
('React - The Complete Guide', 'Udemy', 'https://udemy.com/react', ARRAY['React', 'Hooks', 'Redux', 'Next.js'], 'paid'),
('freeCodeCamp Web Development', 'freeCodeCamp', 'https://freecodecamp.org', ARRAY['HTML', 'CSS', 'JavaScript', 'React'], 'free'),
('The Odin Project', 'The Odin Project', 'https://theodinproject.com', ARRAY['HTML', 'CSS', 'JavaScript', 'Node.js', 'Git'], 'free'),
('Node.js - The Complete Guide', 'Udemy', 'https://udemy.com/nodejs', ARRAY['Node.js', 'Express', 'MongoDB', 'REST APIs'], 'paid'),
('TypeScript Fundamentals', 'Pluralsight', 'https://pluralsight.com/typescript', ARRAY['TypeScript', 'JavaScript', 'Type Systems'], 'paid'),
('CSS Grid and Flexbox', 'Scrimba', 'https://scrimba.com/css', ARRAY['CSS', 'Responsive Design', 'Layout'], 'free'),

-- Data Science & Analytics
('Python for Data Science', 'Coursera', 'https://coursera.org/python-data', ARRAY['Python', 'Pandas', 'NumPy', 'Matplotlib'], 'paid'),
('Machine Learning Specialization', 'Coursera', 'https://coursera.org/ml', ARRAY['Machine Learning', 'Python', 'TensorFlow', 'Deep Learning'], 'paid'),
('SQL for Data Analysis', 'Udacity', 'https://udacity.com/sql', ARRAY['SQL', 'Database Design', 'Data Analysis'], 'free'),
('Data Analysis with Python', 'freeCodeCamp', 'https://freecodecamp.org/data-analysis', ARRAY['Python', 'Pandas', 'Data Visualization', 'NumPy'], 'free'),
('Statistics for Data Science', 'Khan Academy', 'https://khanacademy.org/statistics', ARRAY['Statistics', 'Probability', 'Data Analysis'], 'free'),
('Tableau Fundamentals', 'Tableau', 'https://tableau.com/learn', ARRAY['Tableau', 'Data Visualization', 'Dashboards'], 'free'),
('Excel Skills for Business', 'Coursera', 'https://coursera.org/excel', ARRAY['Excel', 'Data Analysis', 'Pivot Tables', 'Charts'], 'paid'),
('Big Data Essentials', 'Coursera', 'https://coursera.org/bigdata', ARRAY['Hadoop', 'Spark', 'Big Data', 'Data Engineering'], 'paid'),

-- Design
('UI/UX Design Specialization', 'Coursera', 'https://coursera.org/ui-ux', ARRAY['UI Design', 'UX Design', 'Figma', 'User Research'], 'paid'),
('Figma Masterclass', 'Udemy', 'https://udemy.com/figma', ARRAY['Figma', 'Prototyping', 'UI Design'], 'paid'),
('Graphic Design Basics', 'Skillshare', 'https://skillshare.com/graphic-design', ARRAY['Graphic Design', 'Adobe Photoshop', 'Illustrator'], 'paid'),
('Web Design for Beginners', 'YouTube', 'https://youtube.com/web-design', ARRAY['Web Design', 'HTML', 'CSS', 'Figma'], 'free'),
('Adobe XD Tutorial', 'Adobe', 'https://adobe.com/xd/learn', ARRAY['Adobe XD', 'Prototyping', 'UI Design'], 'free'),
('Design Thinking Fundamentals', 'Interaction Design Foundation', 'https://interaction-design.org', ARRAY['Design Thinking', 'User Research', 'Ideation'], 'paid'),
('Color Theory for Designers', 'Coursera', 'https://coursera.org/color-theory', ARRAY['Color Theory', 'Visual Design', 'Branding'], 'free'),

-- Digital Marketing
('Digital Marketing Specialization', 'Coursera', 'https://coursera.org/digital-marketing', ARRAY['SEO', 'Social Media', 'Content Marketing', 'Analytics'], 'paid'),
('Google Analytics for Beginners', 'Google', 'https://analytics.google.com/courses', ARRAY['Google Analytics', 'Web Analytics', 'Data Analysis'], 'free'),
('SEO Training Course', 'Moz', 'https://moz.com/learn/seo', ARRAY['SEO', 'Keyword Research', 'Link Building'], 'free'),
('Social Media Marketing', 'HubSpot Academy', 'https://academy.hubspot.com', ARRAY['Social Media Strategy', 'Content Creation', 'Social Media Analytics'], 'free'),
('Content Marketing Certification', 'HubSpot Academy', 'https://academy.hubspot.com/content', ARRAY['Content Marketing', 'Copywriting', 'Content Strategy'], 'free'),
('Email Marketing Mastery', 'Udemy', 'https://udemy.com/email-marketing', ARRAY['Email Marketing', 'Marketing Automation', 'Copywriting'], 'paid'),
('Facebook Ads & Marketing', 'Udemy', 'https://udemy.com/facebook-ads', ARRAY['Facebook Ads', 'Social Media Advertising', 'PPC'], 'paid'),
('Google Ads Certification', 'Google', 'https://skillshop.withgoogle.com', ARRAY['Google Ads', 'PPC', 'Search Marketing'], 'free'),

-- General Skills
('Git & GitHub Crash Course', 'YouTube', 'https://youtube.com/git-github', ARRAY['Git', 'GitHub', 'Version Control'], 'free'),
('Agile Project Management', 'Coursera', 'https://coursera.org/agile', ARRAY['Agile', 'Scrum', 'Project Management'], 'paid'),
('Docker and Kubernetes', 'Udemy', 'https://udemy.com/docker-kubernetes', ARRAY['Docker', 'Kubernetes', 'DevOps', 'Containers'], 'paid'),
('AWS Fundamentals', 'AWS Training', 'https://aws.training', ARRAY['AWS', 'Cloud Computing', 'Infrastructure'], 'free'),
('REST API Design', 'Udemy', 'https://udemy.com/rest-api', ARRAY['REST APIs', 'API Design', 'Backend Development'], 'paid');


COMMIT;
